### PR TITLE
Update to use .NET 8 RTM

### PR DESCRIPTION
**Pull request by ErikEJ**
Update test dependencies

Use 8.0 System.Configuration.ConfigurationManager that has less dependencies than the the 6.0 version (including System.Common.Drawing!)

### CODE REVIEW

**Comment by ErikEJ** [comment]
@roji @bricelam FYI

**Comment by ErikEJ** [comment]
@roji Thoughts?

**Comment by roji** [comment]
@ErikEJ this definitely looks OK to me - I can merge it, but I don't think I have permissions to publish the nuget...

@bricelam are you interested in continuing to maintain this etc.?

**Comment by ErikEJ** [comment]
If not I am happy to help and support

**Comment by roji** [comment]
If @bricelam is good with it, I think we'd be happy for you to take over this!

**Review by roji — APPROVED** [review]
LGTM.

Just a thought - we could align the versions of this library to the version of EF it requires, like for EFCore.NamingConventions/CheckConstraints (rather than have a table that tells you which version goes with which).

**Comment by bricelam** [comment]
Wait, what's the value here? If you have EF8 installed, then add the 2.0 version of this package won't the end result be the same?

With this package and my pluralizer, I've avoided publishing any new versions unless they actually get broken by EF.

**Comment by bricelam** [comment]
P.S. Sorry for my limited availability lately. Life's been really busy. It's not an intentional absence, and hopefully it's just a point-in-time thing.

**Comment by bricelam** [comment]
> @bricelam are you interested in continuing to maintain this etc.?

Yes. Unless the EF Team thinks I'm doing a bad job or disagrees with my decisions for it--then I'm happy to relinquish it to them.

**Comment by ErikEJ** [comment]
@bricelam 

 > won't the end result be the same?

Not exactly:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.ConfigurationManager" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
  </ItemGroup>

</Project>
```
Publish:

image

Then add:

`<PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />`

Publish:

image

**Comment by bricelam** [comment]
Alright. Yeah, I'm fine shipping this.

**Pull request merged**
